[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "52b9422ce7c694c1ae8e4b014c76aa552bbb2cc9"
os = "macos"

    [[HiGHS.download]]
    sha256 = "74f24e72ad9d5b11370974b5e88a757c801aa811902a7c5ec6ef558a7c518017"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.aarch64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "664e3659d6b26b70e764cb87b2ba2e87a33e2053"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "4a3896be8bfc450d77006e49d107e274ad929784557547221d9b603bd5a31f7c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "254fdbe1f6913b8e74f87f39716b0882d845b6a0"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "685119b9960dc0e1b87fcc1503b7608507e6a03232e124eba909948a3f908cad"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "97617667bf70e6664d04fb2cac34049a72214c8e"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "34fa73cb4e860961bb93f6b8ce70621364615996fbc70ed9d86c781ae5d0b975"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.aarch64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "039596591515d5ff834d9250ed02bd506a42c047"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "c7cbb1eac8ad2811fa97c7407a5eed8c04f74ea38cb23f67e2450b98aa2b63bf"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "391a4e0069e3082b940904f8275cca826b7184a4"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "3db3354ebfea467890a2b06b3f69b740574429c44d9219f3b0a7fd3164fe5877"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ef30631e00045d474231098b0e3b304f76b780"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "30821fe06056311d7b84ece5226fd21544b4f7d25437fe349c84190721a12007"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d926021c41415c185f3280a6bd2ad324c3190a6"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "030d39d1997ac42d4494c6f6e057e0a429444fd0c8d8f92d3aec018207be1f39"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fa587eaf98a951d1897becb4dbec69144a6bf51"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "d86645dc965385531d3addd230e2b948a3d561663874211e04b81b3c185260ae"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5620559c1e34f1c9a969abe21734202bbecb61b"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "f8d5932ad6bc24985d0aba23ef878b1773864d94ae707d12c3fb865feb57f31c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5412e3ee2848bc5b18599ae682ae0cc04cd90cb"
os = "windows"

    [[HiGHS.download]]
    sha256 = "ad5926fcc00cee588de7b417087da53d89f65b907fa804e3ada98ac62a6e950d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.i686-w64-mingw32-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "b3aebe1ddadb2b301e95331706219d432d57b5b2"
os = "macos"

    [[HiGHS.download]]
    sha256 = "ebbb31118d34eaaec93ba583c7ebac5499a06c6dd5b1d7028b1bc85c77a869ae"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.x86_64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d3326352406f6bf898ef4f7077003d99787f0df"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "2058c4f7193190fb08d711c959706c909a93577977e0fd530683625efa59c2a0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952e70a7b7a61714db0fa0b10d3851da2e51e2b5"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "51e281beb4ee6766c26e139b9b6421d2b725e700ec32c80df00ee5991dc42bd3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "234c5b7d84330d6ff686e7e7c4632d8d8b23d1dd"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "91d35848883713b63357571e139926e5923374707083a7e829d8ebf40452f73c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdca6ce413064872d03b062ef474040476b9a846"
os = "windows"

    [[HiGHS.download]]
    sha256 = "b3ad0718e882583442a1e8ab2c1938ac1312fe063c51a85ebb406409f004e40f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.0+0/HiGHS.v1.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
