[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "c8a6d2a5282de085c0627d9125ac9a3a4d03fb62"
os = "macos"

    [[HiGHS.download]]
    sha256 = "2899103ebd9937b1d72b0aba3e857004468aa26a4ad66533690491429eee01c6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.aarch64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c2e247866a7b14f4ca9386c13b2043d17fb06e3"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "6789c2d2f671bcbbf1c84b8220c34a730746c3e4049bae8d2fb2feae249d9836"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3fd0424a1e93ae4eb193bb49f1b2017e2609df3"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "2c0667bff531ac84794448f1b086fe6937e582822a35c9bcf27333835a5672c7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "fe07eab04926a7333a5203a4e4ea450c74295a8f"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "9df277494d47935813cc1cdab62a47519a40f1ddfaa264201ac35bd7104abb69"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.aarch64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be2c767e6fc1f4299e544685fec7bec7148370a9"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "c8521206a09378078d1bd4cd79fcc4d22e51e9bc96ad1ae41685e994e4e64226"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fefe79878873ccfd24659bdd98cae6f5f4a2520"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "6f85c589837335108c60f14764cf52486754cdd766b513de6dba229909f41b6f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d08ff62a7c6b84b7ffe29818ecd9e3239f7f9d8d"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "9c752cf60d06394b5a24f3ddefaedd529f103ef60e7e8195803559c214f6745d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4eac828c829cf3affa2b4b73630fd8e276851c6c"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "541e173bc8ddc4265899b5e8788155cc1735241e6220193c5d0b18ed2df4d885"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35346b57f77bad3f2840e09458bb519964690fde"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "3f9af3f2198156997638d6e3c4a7cfb801afa8c9ac69f38d292e4e4d570ffeaa"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7ec1251f8501b3642a2b7bee1254226ab2c0a48"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "a9babb1bfd9f869e44b2a6a9d4bf6883a70f66b263459d3667080de77b408f0d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4d612c23c1f2bf8ca5349513d3db9751d9fabbb"
os = "windows"

    [[HiGHS.download]]
    sha256 = "79e4ab074c358b4057b0132c4a0bc633e7741c3c52bfbddf7251dc515dda4498"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.i686-w64-mingw32-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "769b13d7e8d195cd570105fe4e8a1f8f72a8a2be"
os = "macos"

    [[HiGHS.download]]
    sha256 = "ac680843ccba0025dea7df3c3acf246112e6c2b93d5a46ade0bbea80f39d8414"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.x86_64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f5853b2f0786049f8ae5d642f412a7a73bfad68"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "4dc368d7661673215de9ffd0584fa0dfac28f10219c6466de96db12f1819d662"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8c702b57af0e439320fa3b3a42223b77f83e6b8"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "c01e354c4b20733f9ba50f125e8dd8fd56d869359056cc9f439971360ca76773"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "f3b800fa3c02d9c88471c6816713146d47190f01"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "125e0e4e251a565de9c8c1bc2b13ea8ada40fa003475f2f432d27c5394d345cd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "955796be7e749f7752ded5f8fd07238c8319d954"
os = "windows"

    [[HiGHS.download]]
    sha256 = "bcfa0706b4eddc3c6594c131959db913c2cfb855f597df798b26ae14838db919"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.14.0+0/HiGHS.v1.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
