[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "d8d1e4290eec99e822d956b088e1e859825ac22b"
os = "macos"

    [[HiGHS.download]]
    sha256 = "fe0716122be413881215380d6008efb334d08f12b4c5aafc59667bafceacc2df"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.aarch64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a0d3c99dd6978a6d9812507f18a80013d859570"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "bf85e706486effeeb99c4e4a831d3e727356616c62cbf22a2e2a5a284f47c9a8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34b5e5e47d443bc518e4117ae9bf8598883e7211"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "3b3b50d56893558ea03db93759b2ea22642ebc10bf6340c6fdd374f1964cf425"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "b2db1e1e84e543d6a33b06359da8d86232c62acd"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "d2f62885ea434370f0cb99ed35f3450c9eb1015fa0cd1dc30a9839d7e98be99a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.aarch64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ed9c6989bed921acb94b434b5fd7025a68641e0"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "81b5e597a0c6c9d35f5d7d14538f05f6180a0ee8adfc3e2f764f33bfc40bab9e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17a855b004b902d7e50bc72c6b0a5913f3b0ef9a"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "2d50824c971399128812e1118bf8be8faa436f4ab5edf5fe8701755987f0686e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c68d96e39ab691274d42e51250add7f311cf24b8"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "fbfe0cb65a50b40f01aa9e889aa8adabd0b1c139b4f3225a50934fb7929bc49b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d82e91158ae18f132474b69fb4199aadc6f83a83"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "c58f129b99848a3c483a79fed539f8f003d897b20351a9e07baac9463fbe822c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6127867bc1d60915253c193148a8b93290bbbe3"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "dfd2e865476fd480a03cab8873b9e07a76079765cdf623c8d452c6a3c00e9788"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.i686-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91aa83e9212c7bf97a861688f5ec1ea6f62b37cc"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "430df2f80b7a69bb39af55f13c1eaa0dcdd61055ace85833e9123fa9eab9f1a7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.i686-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4369076e38f5d197396d124344338b80c66e61ef"
os = "windows"

    [[HiGHS.download]]
    sha256 = "4269280bfd10d7422022238833057a28662413edc9bab184782cb2e6375111b0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.i686-w64-mingw32-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "b94b3067224ce5bee69d23cbd9093eb1c7cea6a3"
os = "macos"

    [[HiGHS.download]]
    sha256 = "6e55b3b17ff5aebf2983bbce9aa575ea2351efc0a0ef15277a68a0635a216e9b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.x86_64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd345ac299fa48818efe3b36a1827d43ac7b3f00"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "70b363ff1b3a131466376023003641190cc47b79876bd143fc953d737201f3fb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f3c23b713cda4761d23814553b25d5fd13760bc"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "bdf8fc19565eb2ca01835358c6fcd4d722e31a6d9f39e1425714046a279dc530"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "248b6339301833ea56bb492446c5a73f10dbac6e"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "e9ffe09f2ede57e0129274106b0b2510cce28036ff5d17d76c48cf381d366b5e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.x86_64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6be445243057a736ee559e33b368841ca1eb466"
os = "windows"

    [[HiGHS.download]]
    sha256 = "4d9ee87e1c5d00b0276d20e9538a207eb0ddfaa0908b33829af01c3cb1257e9d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.15.1+1/HiGHS.v1.15.1.x86_64-w64-mingw32-cxx11.tar.gz"
