# Autogenerated wrapper script for HiGHS_jll for i686-w64-mingw32-cxx03
export highs, libhighs

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("HiGHS")
JLLWrappers.@declare_executable_product(highs)
JLLWrappers.@declare_library_product(libhighs, "libhighs.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        highs,
        "bin\\highs.exe",
    )

    JLLWrappers.@init_library_product(
        libhighs,
        "bin\\libhighs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
