# Autogenerated wrapper script for HiGHS_jll for i686-w64-mingw32-cxx11
export highs, libhighs

using CompilerSupportLibraries_jll
using Zlib_jll
using METIS_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("HiGHS")
JLLWrappers.@declare_library_product(libhighs, "libhighs.dll")
JLLWrappers.@declare_executable_product(highs)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll, METIS_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libhighs,
        "bin\\libhighs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        highs,
        "bin\\highs.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
