# Autogenerated wrapper script for HiGHS_jll for x86_64-apple-darwin
export highs, libhighs

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("HiGHS")
JLLWrappers.@declare_executable_product(highs)
JLLWrappers.@declare_library_product(libhighs, "@rpath/libhighs.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        highs,
        "bin/highs",
    )

    JLLWrappers.@init_library_product(
        libhighs,
        "lib/libhighs.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
